const PRODUCTS = [
  {
    "id": "ame-f01",
    "sku": "ARB-OUDL-SET2",
    "nameAr": "طقم عطر وبخاخ جسم عود الليل - قطعتين",
    "nameEn": "Oud Al Layl Perfume & Body Spray Set - 2 Pcs",
    "category": "Perfumes",
    "image": "images/ARB-OUDL-SET2.jpg",
    "packAr": "دسته (علبة تحتوى قطعتين)",
    "unitAr": "دسته",
    "retailPrice": 698,
    "wholesalePrice": 586,
    "bulkPrice": 550,
    "wholesaleMinQty": 10,
    "bulkMinQty": 40,
    "descriptionAr": "العلامة التجارية: Arabiyat by My Perfumes (عربيات من ماي برفيومز).\n- الإصدار: Oud Al Layl (عود الليل).\n- محتويات الطقم:\n- عطر (Eau de Parfum) حجم 100 مل.\n- بخاخ معطر للجسم (Perfume Spray) حجم 200 مل.\n- الفئة المستهدفة: للجنسين.",
    "stockQty": 100
  },
  {
    "id": "ame-f02",
    "sku": "ARB-IMUSK-SET2",
    "nameAr": "طقم عطر وبخاخ جسم مسك مركز - قطعتين",
    "nameEn": "Intense Musk Perfume & Body Spray Set - 2 Pcs",
    "category": "food",
    "image": "🌴images/ARB-IMUSK-SET2.jpg",
    "packAr": "كرتونة تحتوي على 5 قطع",
    "unitAr": "كرتونة",
    "retailPrice": 698,
    "wholesalePrice": 586,
    "bulkPrice": 550,
    "wholesaleMinQty": 12,
    "bulkMinQty": 48,
    "descriptionAr": "- العلامة التجارية: Arabiyat by My Perfumes (عربيات من ماي برفيومز).\n- الإصدار: Intense Musk (مسك مركز).\nمحتويات الطقم:\n- عطر (Eau de Parfum) حجم 100 مل.\n- بخاخ معطر للجسم (Perfume Spray) حجم 200 مل.\n- الفئة المستهدفة: للجنسين.",
    "stockQty": 100
  },
  {
    "id": "ame-f03",
    "sku": "ARB-KOW-SET2",
    "nameAr": "طقم عطر وبخاخ جسم خشب والعود \"أبيض\" - قطعتين",
    "nameEn": "Khashab & Oud White Perfume & Body Spray Set - 2 Pcs",
    "category": "Perfumes",
    "image": "images/ARB-KOW-SET2.jpg",
    "packAr": "كرتونة تحتوي على 5 قطع",
    "unitAr": "كرتونة",
    "retailPrice": 698,
    "wholesalePrice": 586,
    "bulkPrice": 550,
    "wholesaleMinQty": 15,
    "bulkMinQty": 50,
    "descriptionAr": "- العلامة التجارية: Arabiyat by My Perfumes (عربيات من ماي برفيومز).\n- الإصدار: Khashab & Oud White (خشب والعود - أبيض).\nمحتويات الطقم:\n- عطر (Eau de Parfum) حجم 100 مل.\n- بخاخ معطر للجسم (Perfume Spray) حجم 200 مل.\n- الفئة المستهدفة: للجنسين (مناسب للرجال والنساء).",
    "stockQty": 100
  },
  {
    "id": "ame-h01",
    "sku": "SKU-LCH-S10",
    "nameAr": "ملايات فنادق قطن قطيفة 100% كينج",
    "nameEn": "Luxury Hotel Bed Sheets 100% Cotton",
    "category": "hotel",
    "image": "🛏️",
    "packAr": "حزمة من 10 ملايات مقاس ملكي 240×260",
    "retailPrice": 4800,
    "wholesalePrice": 4100,
    "bulkPrice": 3600,
    "wholesaleMinQty": 5,
    "bulkMinQty": 15,
    "unitAr": "حزمة",
    "descriptionAr": "مفروشات فاخرة للفنادق والمنتجعات ذات الخمس نجوم.\n- قطن مصري طويل التيلة ١٠٠٪ بنعومة فائقة.\n- مقاومة عالية للكسر والبهتان وغسيل الصناعي والكلور.\n- حاشية معززة وخياطة مزدوجة لمتانة استثنائية.",
    "stockQty": 340
  },
  {
    "id": "ame-h02",
    "sku": "SKU-GEL-B10",
    "nameAr": "كراسي قاعات وحفلات مذهبة ثقيلة",
    "nameEn": "Heavy-Duty Gilded Banquet Chairs",
    "category": "hotel",
    "image": "🪑",
    "packAr": "طقم مكون من 10 كراسي فولاذية مذهبة",
    "retailPrice": 13500,
    "wholesalePrice": 11900,
    "bulkPrice": 10800,
    "wholesaleMinQty": 4,
    "bulkMinQty": 12,
    "unitAr": "طقم",
    "descriptionAr": "كراسي مؤتمرات وقاعات حفلات فاخرة ومريحة.\n- هيكل صلب وفولاذي ثقيل مطلي بطبقة تذهيب حراري مضادة للخدوش.\n- حشوة دبل إسفنجية عالية الكثافة ومقاومة للاهتراء والانضغاط.\n- تصميم قابل للتكديس والترتيب لتوفير المساحة بالمخازن.",
    "stockQty": 180
  },
  {
    "id": "ame-c01",
    "sku": "SKU-IND-C25",
    "nameAr": "منظف كيميائي سائل للمغاسل والمطابخ",
    "nameEn": "Industrial Multi-Surface Liquid Cleanser",
    "category": "chemicals",
    "image": "🧪",
    "packAr": "برميل صناعي أزرق سعة 25 لتر",
    "retailPrice": 920,
    "wholesalePrice": 790,
    "bulkPrice": 710,
    "wholesaleMinQty": 8,
    "bulkMinQty": 25,
    "unitAr": "برميل",
    "descriptionAr": "تركيبة نشطة تجارية عالية الكفاءة والقوة.\n- تزيل أصعب الدهون، البقع، والترسبات الكلسية بمثالية.\n- تركيبة هيدروكسيدية معززة ومطهرة للأسطح.\n- مركزة للغاية لتمنح قيمة توفير فائقة بعد تخفيفها بالماء.",
    "stockQty": 420
  },
  {
    "id": "ame-c02",
    "sku": "SKU-ALC-S70",
    "nameAr": "مستحضر معقم الكحول الفاخر (رغوي)",
    "nameEn": "Royal Foaming Hand Sanitizer Bulk",
    "category": "chemicals",
    "image": "🧴",
    "packAr": "كرتونة تحتوي على 4 جالونات × 5 لتر",
    "retailPrice": 1250,
    "wholesalePrice": 1050,
    "bulkPrice": 960,
    "wholesaleMinQty": 10,
    "bulkMinQty": 30,
    "unitAr": "كرتونة",
    "descriptionAr": "معقم ميكروبي كحولي رغوي آمن ولطيف على البشرة.\n- نسبة كحول إيثيلي نقي ٧٠٪ للحماية من الجراثيم والفيروسات.\n- معزز بخلاصة الجلسرين لمنع جفاف وتهيج الأيدي.\n- مثالي لمحطات التوزيع والموزعات الآلية بالفنادق والمطارات.",
    "stockQty": 550
  },
  {
    "id": "ame-u01",
    "sku": "SKU-MBN-B01",
    "nameAr": "سرير عمال حديدي دورين ثقيل",
    "nameEn": "Heavy-Duty Metal Double Bunk Bed",
    "category": "furniture",
    "image": "🛌",
    "packAr": "هيكل واحد حديد سميك مقاوم للاهتزاز",
    "retailPrice": 4600,
    "wholesalePrice": 3950,
    "bulkPrice": 3500,
    "wholesaleMinQty": 10,
    "bulkMinQty": 35,
    "unitAr": "هيكل",
    "descriptionAr": "سرير عمال حديدي دورين فائق القوة والصلابة.\n- مصنع بالكامل من حديد كربوني مقاوم للاهتراء والالتواء والصدأ.\n- دعامات تسليح إضافية لمنع الاهتزاز والأصوات المزعجة.\n- مطلي حرارياً بطبقة مقاومة للرطوبة والبكتيريا.",
    "stockQty": 290
  },
  {
    "id": "ame-u02",
    "sku": "SKU-MTL-L06",
    "nameAr": "خزائن عمال معدنية 6 فتحات مع قفل",
    "nameEn": "6-Compartment Reinforced Metal Locker",
    "category": "furniture",
    "image": "🗄️",
    "packAr": "وحدة تخزين واحدة منفصلة بقفل أمان",
    "retailPrice": 5800,
    "wholesalePrice": 5100,
    "bulkPrice": 4600,
    "wholesaleMinQty": 5,
    "bulkMinQty": 15,
    "unitAr": "وحدة",
    "descriptionAr": "خزائن تخزين صلبة آمنة متعددة الفتحات.\n- مقسمة إلى ٦ فتحات مستقلة متسعة مع فتحات تهوية صحية.\n- هيكل ملحوم شديد الصلابة ومقاوم للصدمات والخدش.\n- مزيج حماية حديدي ثلاثي النقاط مع حلقة قفل للامتعة الشخصية.",
    "stockQty": 140
  }
];
